version: '3.7'

networks:
  app:
    driver: bridge

services:
  workspace:
    build:
      context: ./workspace
      args:
        - PHP_VERSION=${PHP_VERSION}
    image: ${COMPOSE_PROJECT_NAME}_workspace:latest
    volumes:
      - ${PROJECT_PATH}:/var/htdocs
    tty: true
    networks:
      - app
